### ISSUE TITLE
Doesn't reboot without pulling the plug

### ISSUE THREAD

**Issue by timjp87** [longsleep/snappy-odroidc#1]
Hello,

thank you for bringing Ubuntu Snappy Core to the ODROID-C1. 
I followed the instructions and created a 16 GB image, which I dd'ed onto my sdcard.
The image was created from the edge channel on 15.04 with --developer-mode and --enable-ssh.

When I log in via SSH and issue "sudo reboot" the device goes down (I can't connect via SSH or ping it), but it never comes back up. Even after 5 minutes there is still some blinking of the blue LED going on. When I replug the power I connect again after some 30 seconds. Unfortunately I don't have any way to get logs from the shutdown sequence. "sudo journalctl --list-boots" only lists the current boot.

**Comment by longsleep** [comment]
Thanks for testing! I do not have see this problem. May be you can try with a serial console attached and see what is going no in detail.

**Comment by timjp87** [comment]
I don't have a serial conosle yet, but I ordered the USB-UART Module from pollin.de.

**Comment by longsleep** [comment]
Probably not related, but the U-Boot fat write support i patched in seems sometimes destroys the fat partition. Maybe it is related - the U-Boot probably needs another set of patches from upstream to make this problem go away. If the fat partition is bad, U-Boot will not boot.

**Comment by longsleep** [comment]
I cherry-picked a bunch of FAT write U-Boot fixes. Make sure to pull and build a new U-Boot.

**Comment by timjp87** [comment]
I tried the latest commit on a fresh image, but no luck. Still stops with the blinking blue led.

**Comment by longsleep** [comment]
Mhm - not much more to tell without a serial console. I never had this problem while testing. I will provide a image download soon. Maybe something is different in your builds.

**Comment by longsleep** [comment]
Check out my pre-built image at https://www.stdin.xyz/downloads/snappy/odroidc/

**Comment by timjp87** [comment]
Your image does work for me. After "sudo reboot" I can ping the device after a few seconds again and ssh in after a few more seconds. Strange.

This is how I created the image:
1. Booted a USB stick with Ubuntu MATE 15.04 live environment since I don't use Ubuntu as desktop distro
2. Plugged in an external drive and mounted it so I don't run out of space when the kernel sources are built and stuff is downloaded.
3. Added the snappy-tools PPA and installed the tools to have ubuntu-device-flash
4. Installed the build requirements listed in your Readme of this Github repo.
5. Cloned the repo onto the external drive.
6. Run make
7. Run ssh-keygen otherwise creating developer mode image won't work for some reason
8. Run sudo ubuntu-device-flash with the oem and device-parts. I add --enable-ssh, since I read this on the Ubuntu snappy porting guide. I'm not sure if thats redundant with developer-mode.
9. I unmount and unplug the external drive after the image was created and plug it into my old laptop (building on this thing would take hours), since it has an SD Card reader.
10. sudo ddrescue -d -D --force myimage.img /dev/mmcblk0 (same as I did with your image)

I have two SD cards 8 and 16 GB, I tried both once with an 8 and 16 GB image. Now I have your 4 GB image on the 8 GB card, which works...

Strange.

**Comment by longsleep** [comment]
Well that is something. You can try to build a image again from scratch (make distclean, make clean). Maybe it is related to image size - no idea. I am really interested to know about the reason for this error but i guess we have to wait until you have the USB-UART adapter.

I also might eventually provide a Dockerfile to simplify compilation on non Ubuntu installations.

**Comment by timjp87** [comment]
Odd. So I made a new image. This time 4 GB just as yours and flashed it to the 16 GB sd card (I have yours on the 8 GB card). I boots, but doesn't reboot. I put the 8 GB card with your 4 GB image in, but it doesn't even boot anymore. When I tried it I was able to reboot it multiple times and even assign a static IP and connect to that and reboot. My Revision of the ODROID-C1 is 0.3 20141107.
It also looks like when I try to reboot it actually powers down shortly the Ethernet LEDs go out for a second and come back up. Have to wait for my adapter and some freetime.

**Comment by longsleep** [comment]
I think there is only this revions of ODROID-C1. 

I have released a first image based on stable channel - i suggest you use that one. See https://www.stdin.xyz/2015/06/14/snappy-ubuntu-core-for-odroid-c1/ for details

**Comment by timjp87** [comment]
Just received my USB-UART module and rebuilt everything with the latest commit and made two images one 8 GB and one 15 (I tried 16 for the other sd card once, but it wouldn't fit because of a few MB). I flashed the 8 GB image on the 8GB card and it works perfectly. I rebooted multiple times. Used "sudo poweroff" and did a cold boot a few times and one time just pulled the plug from the booted system and was able to boot and reboot after that just fine.

I tried the 16 GB card with the 15 GB image and tried to reboot directly after its first boot and it didn't work. It looks like it powers down and boots, but the terminal starts to spam error messages at some point and stops at the last line in the log.

http://pastebin.com/8FDu0vh7 Line 1245 and 2098

It looks like it doesn't like the 16 GB Kingston SD Card. I'll now flash the same 8 GB image which works on the 8 GB card to the 16 GB card. I'm pretty sure that at one point in the past I couldn't reboot the system with either of both cards.

EDIT: I also doesn't work with the 8GB image on the 16 GB card. I had Arch Linux ARM on it a few months ago which works just fine.

EDIT: ALARM on the 16 GB card with a single 16 GB ext4 partition reboots just fine on this card.

**Comment by longsleep** [comment]
Mhm thats strange. I guess this is more something for the Hardkernel forum then.  You could try to add "disableuhs". Though it already starts with a crc error at the very first boot from your log (**\* Warning - bad CRC, using default environment).

It should look like this

```
* Welcome to Hardkernel's ODROID-C... (Built at 19:33:00 Dec  8 2014) *
-----------------------------------------------------------------------
CPU : AMLogic S805
MEM : 1024MB (DDR3@792MHz)
BID : HKC13C0001
S/N : HKC1CC0349BFADB1
0x0000009f
check SD_boot_type:0x1   card_type:0x1
Loading U-boot...success.


U-boot-00000-gad4d9a6(odroidc@master) (Jun 06 2015 - 18:26:03)

DRAM:  1 GiB
relocation Offset is: 2ff1c000
MMC:   SDCARD: 0, eMMC: 1
IR init is done!
vpu clk_level = 3
set vpu clk: 182150000Hz, readback: 182150000Hz(0x701)
mode = 6  vic = 4
set HDMI vic: 4
mode is: 6
viu chan = 1
config HPLL
config HPLL done
reconfig packet setting done
MMC read: dev # 0, block # 33984, count 12288 ... 12288 blocks read: OK
There is no valid bmp file at the given address
============================================================
Vendor: Man 035344 Snr 0fb4b94e Rev: 8.0 Prod: SE32G
            Type: Removable Hard Disk
            Capacity: 30436.5 MB = 29.7 GB (62333952 x 512)
------------------------------------------------------------
Partition     Start Sector     Num Sectors     Type
    1             8192      131072   c
    2           139264     2097152  83
    3          2236416     2097152  83
    4          4333568     3280896  83
============================================================
```

From above i see that you use ddrescue. I suggest you try using dd.

Something like 'dd if=ubuntu-15.04-snappy-armhf-odroidc_0.3.img.xz | pv | dd of=/dev/sdc bs=1M'

**Comment by longsleep** [comment]
Reading a bit more about possible issues with sdcards i am quite confident that your card does not work with uhs. To disable it, add the `disableuhs` parameter to the mmcargs command parameter list in boot.ini. You can do that directly on the sdcard without creating a new image. I will add example (commented) to the boot.ini.

**Comment by timjp87** [comment]
Great. Everything works now even with my 16 GB SD Card. Thanks!
