### ISSUE TITLE
"sudo: unable to resolve host odroid" when using sudo

### ISSUE THREAD

**Issue by timjp87** [longsleep/snappy-odroidc#2]
I get this message every time I use sudo.

I fixed it by chaning the first line in /etc/hosts to:
127.0.0.1   localhost.localdomain odroid    

I don't think these changes are persitent, though and on my other machines /etc/hosts is configured to:
127.0.0.1   localhost.localdomain localhost

and I don't get such messages.

**Comment by longsleep** [comment]
Yes - i am not sure how to solve this problem. The host name is part of the device tree, but snappy image creation does not add it to /etc/hosts - i am still new to snapp, so if there is a way to handle this, please let me know. I will add a bug to snappy if i do not find a solution myself.

**Comment by longsleep** [comment]
Added it to the Snappy tracker at https://bugs.launchpad.net/snappy/+bug/1464396 - please add all further comments there.
