### ISSUE TITLE
"seccomp_load failed with -22 seccomp_load_filters failed with -22" when trying to use docker

### ISSUE THREAD

**Issue by timjp87** [longsleep/snappy-odroidc#3]
When I install docker with:
sudo snappy install docker

and use the command "docker" or "sudo docker" or "docker search tutorial" I get:

seccomp_load failed with -22
seccomp_load_filters failed with -22
. errmsg: Invalid argument

Here is the output of journalctl:
http://pastebin.com/ZXSJs2sw

Could it be that some kernel configs required for snappy are not enabled?
I also installed webdm, which seems to run fine as a service on this device.

**Comment by longsleep** [comment]
Snappy needs apparmor3 to be fully operational. I have not patched the Kernel yet to have it. This is coming on the weekend. In the mean time you could try to build with this tree http://kernel.ubuntu.com/git/ppisati/ubuntu-vivid.git/log/?h=snappy_odroidc with the snappy_odroidc_defconfig config settings and fuse that in your image. It is not up to date, but should have the apparmor3 requirements.

**Comment by longsleep** [comment]
The Kernel tree was moved to my own and the config for this problem was added (https://github.com/longsleep/ubuntu-odroidc/commit/dc66621b6cf2ae0434a89b6f339ca8f5976d4efb) - make sure to change your linux fork to new target or 'make distclean'.
